### ISSUE TITLE
Images shrink when you type more text into a turn

### ISSUE THREAD

**Issue by briandk** [briandk/transdown#36]
The more text I type into a turn, the more any associated image column shrinks rightward.

The fix, it turns out, was to [specify a minimum width][1] for images (5659e4ed7cf9e5d500026297936957bec88dcaa7):

```css
img.accompanying-media {
    min-width: 100px;;
}
```

[1]: https://github.com/briandk/transdown/blob/5659e4ed7cf9e5d500026297936957bec88dcaa7/stylesheets/markedApp/transdownMarkedPreview.css#L16-L18
